[package]
name = "summit"
version = "0.1.0"
edition = "2021"
publish = false
license = "CC BY-NC-SA 4.0"

[dependencies.dioxus]
version = "0.7.0"
features = ["router", "fullstack"]

[dependencies.modwire]
version = "0.1.0"

[dependencies.kore]
version = "0.1.0"
git = "https://github.com/unsudo-org/kore.git"

[dependencies.gloo-timers]
version = "0.3.0"
features = ["futures"]

[dependencies.fastrand]
version = "2.3.0"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
