use super::*;

pub static BAN: Asset = asset!("/asset/icon/cursor/ban.svg");
pub static CLICK: Asset = asset!("/asset/icon/cursor/click.svg");
pub static DEFAULT: Asset = asset!("/asset/icon/cursor/default.svg");
pub static DISABLED: Asset = asset!("/asset/icon/cursor/disabled.svg");
pub static FINGER: Asset = asset!("/asset/icon/cursor/finger.svg");
pub static FINGER_DISABLED: Asset = asset!("/asset/icon/cursor/finger_disabled.svg");
pub static GRIP: Asset = asset!("/asset/icon/cursor/grip.svg");
pub static GRIP_HORIZONTAL: Asset = asset!("/asset/icon/cursor/grip_horizontal.svg");
pub static GRIP_VERTICAL: Asset = asset!("/asset/icon/cursor/grip_vertical.svg");
pub static HAND: Asset = asset!("/asset/icon/cursor/hand.svg");
pub static LOADING: Asset = asset!("/asset/icon/cursor/loading.svg");
pub static MOVE_DIAGONAL: Asset = asset!("/asset/icon/cursor/move_diagonal.svg");
pub static MOVE_DIAGONAL_2: Asset = asset!("/asset/icon/cursor/move_diagonal_2.svg");
pub static MOVE_HORIZONTAL: Asset = asset!("/asset/icon/cursor/move_horizontal.svg");
pub static MOVE_VERTICAL: Asset = asset!("/asset/icon/cursor/move_vertical.svg");
pub static SQUARE: Asset = asset!("/asset/icon/cursor/square.svg");
pub static SQUARE_DASHED: Asset = asset!("/asset/icon/cursor/square_dashed.svg");
pub static TEXT_INPUT: Asset = asset!("/asset/icon/cursor/text_input.svg");
pub static ZOOM_IN: Asset = asset!("/asset/icon/cursor/zoom_in.svg");
pub static ZOOM_OUT: Asset = asset!("/asset/icon/cursor/zoom_out.svg");